import 'package:movie_ticket/data/vos/date_vo.dart';
import 'package:movie_ticket/data/vos/movie_seat_vo.dart';
import 'package:movie_ticket/resources/strings.dart';

List<MovieSeatVO> dummyMovieSeat = [
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "A"),
  MovieSeatVO(type: SEAT_TYPE_EMPTY, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_EMPTY, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "A"),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "B"),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "B"),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "C"),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "C"),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "D"),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "D"),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "E"),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TAKEN, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TAKEN, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TAKEN, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "E"),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "F"),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "F"),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "G"),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_AVAILABLE, title: ""),
  MovieSeatVO(type: SEAT_TYPE_TEXT, title: "G"),
];

List<DateVO> dummyDateList = [
  DateVO(
      day: "Tu",
      date: "29",
      month: "7",
      year: "2021",
      formattedDate: "2021-7-29",
      isSelected: true),
  DateVO(
      day: "We",
      date: "30",
      month: "7",
      year: "2021",
      formattedDate: "2021-7-30",
      isSelected: false),
  DateVO(
      day: "Th",
      date: "31",
      month: "7",
      year: "2021",
      formattedDate: "2021-7-31",
      isSelected: false),
  DateVO(
      day: "Fr",
      date: "1",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-1",
      isSelected: false),
  DateVO(
      day: "Sa",
      date: "2",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-2",
      isSelected: false),
  DateVO(
      day: "Su",
      date: "3",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-3",
      isSelected: false),
  DateVO(
      day: "Mo",
      date: "4",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-4",
      isSelected: false),
  DateVO(
      day: "Tu",
      date: "5",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-5",
      isSelected: false),
  DateVO(
      day: "We",
      date: "6",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-6",
      isSelected: false),
  DateVO(
      day: "Th",
      date: "7",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-7",
      isSelected: false),
  DateVO(
      day: "Fr",
      date: "8",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-8",
      isSelected: false),
  DateVO(
      day: "Sa",
      date: "9",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-9",
      isSelected: false),
  DateVO(
      day: "Su",
      date: "10",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-10",
      isSelected: false),
  DateVO(
      day: "Mo",
      date: "11",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-11",
      isSelected: false),
  DateVO(
      day: "Tu",
      date: "12",
      month: "8",
      year: "2021",
      formattedDate: "2021-8-12",
      isSelected: false),
  DateVO(
      day: "We",
      date: "13",
      month: "",
      year: "2021",
      formattedDate: "2021-8-13",
      isSelected: false),
];
