/// hive type id
const HIVE_TYPE_ID_AUTH_RESPONSE = 1;
const HIVE_TYPE_ID_USER_VO = 2;
const HIVE_TYPE_ID_CARD_VO = 3;
const HIVE_TYPE_ID_MOVIE_VO = 4;
const HIVE_TYPE_ID_CAST_VO = 5;
const HIVE_TYPE_ID_CINEMA_DAY_TIME_SLOT_VO = 6;
const HIVE_TYPE_ID_TIME_SLOT_VO = 7;
const HIVE_TYPE_ID_MOVIE_SEAT_VO = 8;
const HIVE_TYPE_ID_SNACK_VO = 9;
const HIVE_TYPE_ID_PAYMENT_METHOD_VO = 10;
const HIVE_TYPE_ID_TRANSACTION_VO = 11;

/// box name
const BOX_NAME_AUTH_RESPONSE = "BOX_NAME_AUTH_RESPONSE";
const BOX_NAME_USER_VO = "BOX_NAME_USER_VO";
const BOX_NAME_CARD_VO = "BOX_NAME_CARD_VO";
const BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const BOX_NAME_CAST_VO = "BOX_NAME_CAST_VO";
const BOX_NAME_CINEMA_DAY_TIME_SLOT_VO = "BOX_NAME_CINEMA_DAY_TIME_SLOT_VO";
const BOX_NAME_TIME_SLOT_VO = "BOX_NAME_TIME_SLOT_VO";
const BOX_NAME_MOVIE_SEAT_VO = "BOX_NAME_MOVIE_SEAT_VO";
const BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
const BOX_NAME_PAYMENT_METHOD_VO = "BOX_NAME_PAYMENT_METHOD_VO";
const BOX_NAME_TOKEN = "BOX_NAME_TOKEN";
const BOX_NAME_MOVIE_ID = "BOX_NAME_MOVIE_ID";
const BOX_NAME_TRANSACTION_VO = "BOX_NAME_TRANSACTION_VO";

const BOX_NAME_SELECTED_MOVIE_SEAT = "BOX_NAME_SELECTED_MOVIE_SEAT";
const BOX_NAME_SELECTED_SNACK = "BOX_NAME_SELECTED_SNACK";


/// hive key
const MOVIE_ID = "movieId";
const HIVE_USER_KEY = "HIVE_USER_KEY";
